basePath: /v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: Сервис управления настройками информационной системы ГИСОГД
  title: Settings service API
  version: "1.0"
paths: {}
swagger: "2.0"
