@baseUrl = http://localhost:9999/api/v1/settings/

############## ALL SERVICES OPERATIONS #################

# get all records
GET {{baseUrl}} HTTP/1.1

###

# add new service options multiline-string
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "serviceName": "multiline string",
    "options": "{
        \"a\":\"a1\",
        \"b\": {
            \"ba\":\"bbb\"
        },
        \"c\":[
            10,
            11,
            12
        ]
    }"
}

###

# add new service options one-string
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "serviceName": "oneline string",
    "options": "{\"a\":\"a1\",\"b\": {\"ba\":\"bbb\"},\"c\":[10,11,12]}"
}

###

# add new service options json
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "serviceName": "json",
    "options": {
        "a":"a1",
        "b": {
            "ba":"bbb"
        },
        "c":[10,11,12]
    }
}

###

# add public settings from file
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

< ./publicOptionsExample.json

###

############## SINGLE SERVICE OPERATIONS #################

# get settings for service by name
GET {{baseUrl}}testService HTTP/1.1

###

###

# get settings for service by name "newService"
GET {{baseUrl}}newService HTTP/1.1

###

# replace options for "newService"
PUT {{baseUrl}}newService HTTP/1.1
Content-Type: application/json

{
    "options": "{\"a\":\"a3\"}"
}

###

# remove "newService" with options
DELETE {{baseUrl}} HTTP/1.1

###


############## SINGLE FIELD OPERATIONS #################

# change single value in options
PATCH {{baseUrl}}newService/b,ba HTTP/1.1
Content-Type: text/plain

cccccccc

###

# get single field 
GET {{baseUrl}}testService/c,ca HTTP/1.1

###

# delete single field 
DELETE {{baseUrl}}testService/d,1 HTTP/1.1

###
