basePath: /v1
definitions:
  dto.BaseRequest:
    type: object
  dto.HTTPError:
    description: Результат при ошибке
    properties:
      code:
        description: Http-код ответа
        example: 400
        type: integer
      message:
        description: Текст ошибки
        example: Ошибка парсинга
        type: string
    type: object
  dto.ReplaceOptionsRequest:
    description: Замена настроек
    properties:
      options:
        description: Настройки в виде json-строки
        example: '{"c":"ca"}'
        type: string
    required:
    - options
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: Сервис управления настройками информационной системы ГИСОГД
  title: Settings service API
  version: "1.0"
paths:
  /settings:
    get:
      description: Get all service settings JSON as map
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Get all service settings
      tags:
      - settings
    post:
      consumes:
      - application/json
      description: Add complete settings for new service as string by service name
      parameters:
      - description: Options DTO
        in: body
        name: options
        required: true
        schema:
          $ref: '#/definitions/dto.BaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Add complete settings
      tags:
      - settings
  /settings/{serviceName}:
    delete:
      description: Complete remove service settings by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Complete remove service settings
      tags:
      - settings
    get:
      description: Get service settings JSON as string by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Get service settings
      tags:
      - settings
    put:
      description: Completely replace service settings by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Service settings
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/dto.ReplaceOptionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Replace service settings
      tags:
      - settings
  /settings/{serviceName}/{path}:
    delete:
      description: Delete service option by service name and option path
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Option path, comma-separated keys
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Delete concrete service option
      tags:
      - settings
    get:
      description: Get service option as string by service name and option path
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Option path, comma-separated keys
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Get concrete service option
      tags:
      - settings
    patch:
      consumes:
      - text/plain
      description: Update value for service settings by settings key. Set value in
        body with MIME text/plain
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Option path
        in: path
        name: path
        required: true
        type: string
      - description: Option value
        in: body
        name: value
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HTTPError'
      summary: Update service settings
      tags:
      - settings
swagger: "2.0"
