basePath: /v1
definitions:
  dto.GetConcreteOptionRequest:
    description: запрос конкретной настройки
    properties:
      optionPath:
        type: string
    required:
    - optionPath
    type: object
  dto.HttpError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Ошибка парсинга
        type: string
    type: object
  dto.NewOptionsRequest:
    description: Создать значение для сервиса
    properties:
      options:
        description: Настройки в виде json-строки
        example: '{"a":"a3"}'
        type: string
      serviceName:
        description: Имя сервиса
        type: string
    required:
    - options
    - serviceName
    type: object
  dto.ReplaceOptionsRequest:
    description: Замена настроек
    properties:
      options:
        example: '{"c":"ca"}'
        type: string
    required:
    - options
    type: object
  dto.UpdateOptionRequest:
    description: Изменить значение одного поля. Создает поле, если его не существует
    properties:
      optionPath:
        description: Поле для изменения
        example: a/b/c/1
        type: string
      optionValue:
        description: Новое значение
        type: string
    required:
    - optionPath
    - optionValue
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  description: Сервис управления настройками информационной системы ГИСОГД
  title: Settings service API
  version: "1.0"
paths:
  /settings:
    get:
      description: Get all service settings JSON as map
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Get all service settings
      tags:
      - settings
  /settings/:
    post:
      consumes:
      - application/json
      description: Add complete settings for new service as string by service name
      parameters:
      - description: Options DTO
        in: body
        name: options
        required: true
        schema:
          $ref: '#/definitions/dto.NewOptionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Add complete settings
      tags:
      - settings
  /settings/{serviceName}:
    delete:
      description: Complete remove service settings by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Complete remove service settings
      tags:
      - settings
    get:
      description: Get service settings JSON as string by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Get service settings
      tags:
      - settings
    patch:
      description: Update value for service settings by settings key
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Service settings
        in: body
        name: update
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateOptionRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Update service settings
      tags:
      - settings
    post:
      consumes:
      - application/json
      description: Get service option as string by service name and  option path
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Option path
        in: body
        name: path
        required: true
        schema:
          $ref: '#/definitions/dto.GetConcreteOptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Get concrete service option
      tags:
      - settings
    put:
      description: Completely replace service settings by service name
      parameters:
      - description: Service name
        in: path
        name: serviceName
        required: true
        type: string
      - description: Service settings
        in: body
        name: settings
        required: true
        schema:
          $ref: '#/definitions/dto.ReplaceOptionsRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.HttpError'
      summary: Replace service settings
      tags:
      - settings
swagger: "2.0"
